### ISSUE TITLE
link user(s) to client when user type is "Client"

### ISSUE THREAD

**Issue by andrew-macpherson** [andrew-macpherson/netgain-portal#16]
users with a type of "Client" need to be able to see their profile in the system. This includes their user profile as well as the clients they are linked to. A user should be able to be linked to multiple clients. For instance Katie from NAID will need to view / manage the directory, Certification project, MWMA, etc

**Comment by aricm** [comment]
For now it's just just one user to a client. Easiest and quickest way. I'm not sure we really need multiple logins for a client. At least not at first.

Multiple users to a client doesn't make sense unless there will be "sub roles" to limit what the user can do.
